Heap sort using STL functions
OpenLake/Introduction_CPP pull request #13
Opened 2020-10-25 17:03 UTC by deepaks2112

Deepak Singh
11740290
deepaks@iitbhilai.ac.in

2020-10-25 19:03 UTC, shashwatj07 commented
@yatendra1999 another student has already submitted a PR for this function. How to tackle these kind of scenarios?
Also, I don't recommend using STL here. What say?

2020-10-26 19:57 UTC, yatendra1999 commented
Whichever PR is ready to be merged first takes priority. Usage of STL functions is not recommended. Some STL usage is still allowed for data structures and trivial algoritms. In this case, it's not trivial and not allowed.

2020-10-26 19:59 UTC, yatendra1999 requested changes
more work is needed.

2020-10-26 19:59 UTC, yatendra1999 commented on Sorting/heap.cpp
> +	make_heap(sorted.begin(), sorted.begin() + curr_size);
Do not depend on STL to skip major parts of the algorithm.

2020-10-26 19:59 UTC, yatendra1999 commented on Sorting/heap.cpp
> +    	pop_heap(sorted.begin(), sorted.begin() + curr_size);
Same.

2020-10-27 04:05 UTC, closed without merging