added changes to documentation of print function in sorting.cpp
OpenLake/Introduction_CPP pull request #23
Opened 2020-10-26 09:22 UTC by mnswdhw

Manas Wadhwa
11940670

2020-10-26 16:02 UTC, shashwatj07 requested changes
Some items.

2020-10-26 16:02 UTC, shashwatj07 commented on Sorting/sorting.cpp
> + * Depending upon the boolean input, prints the corresponding array separated by comma.When the input is true
```commas. When```

2020-10-26 16:02 UTC, shashwatj07 commented on Sorting/sorting.cpp
> + * Inputs: boolean value True or False
``` boolean, true if the sorted array is to be printed, false for unsorted ```

2020-10-26 19:52 UTC, yatendra1999 commented
Contains the same information in description and the inputs.

2020-10-27 02:07 UTC, shashwatj07 requested changes
Squash your commits into one.

2020-10-27 02:07 UTC, shashwatj07 commented on Sorting/sorting.cpp
> + * it prints the sorted array and when it is false it prints the unsorted array.
```Array Printing Utility```

2020-10-29 16:15 UTC, shashwatj07 commented
@mnswdhw ping

2020-11-01 07:54 UTC, shashwatj07 commented
@mnswdhw ping

2023-03-24 09:53 UTC, closed without merging